#数据连接配置
server:
  port: 8888
  servlet:
    context-path: /thinking
spring:
  application:
    name: thinking
  datasource:
    url: jdbc:mysql://47.94.251.126:3306/thinking?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&useSSL=false&allowPublicKeyRetrieval=true
    password: root
    username: tang1104



#通用配置
common:
  #restTemplate 配置
  rest-template:
    connectTimeout: 150000
    maxTotal: 500
    defaultMaxPerRoute: 100
    requestTimeout: 5000

#窃取个人信息接口配置
filch:
  ipAddress: 'https://api.xywlapi.cc/'
  qqApiUrl: '${filch.ipAddress}qqapi?qq='
  phoneApiUrl: '${filch.ipAddress}qqphone?phone='
  qqLolApiUrl: '${filch.ipAddress}qqlol?qq='
  lolNameApiUrl: '${filch.ipAddress}lolname?name='
  qqLmApiUrl: '${filch.ipAddress}qqlm?qq='
  wbApiUrl: '${filch.ipAddress}wbapi?id='
  wbPhoneApiUrl: '${filch.ipAddress}wbphone?phone='
